#pragma once
#include <fstream>
#include <sstream>
#include <iostream>
#include <string>
using std::cout;
using std::cin;
using std::endl;
using std::string;
using std::stringstream;
using std::fstream;
using std::ios;
using std::ios_base;
string dbg();
string pfx();